-- Script generated by Redgate Compare v1.19.7.13456
SET check_function_bodies = false;


DO language plpgsql $$BEGIN RAISE NOTICE 'Creating public.shipper...';END$$;
CREATE TABLE public.shipper (
    "shipperID" int2vector NOT NULL,
    "shipperName" character varying NOT NULL
);
ALTER TABLE public.shipper ADD CONSTRAINT shipper_pkey PRIMARY KEY ("shipperID", "shipperName");
ALTER TABLE public.shipper OWNER TO postgres;


DO language plpgsql $$BEGIN RAISE NOTICE 'Creating public.product...';END$$;
CREATE TABLE public.product (
    "productID" int2vector NOT NULL,
    "productName" character varying NOT NULL,
    "unitPrice" money NOT NULL
);
ALTER TABLE public.product ADD CONSTRAINT product_pkey PRIMARY KEY ("productID");
ALTER TABLE public.product OWNER TO postgres;


DO language plpgsql $$BEGIN RAISE NOTICE 'Creating public.orderDetails...';END$$;
CREATE TABLE public."orderDetails" (
    "orderID" int2vector NOT NULL,
    "orderDetailID" int2vector NOT NULL,
    "productID" int2vector NOT NULL,
    quantity int2vector NOT NULL,
    "itemPrice" money NOT NULL
);
ALTER TABLE public."orderDetails" ADD CONSTRAINT "orderDetails_pkey" PRIMARY KEY ("orderID", "orderDetailID");
ALTER TABLE public."orderDetails" OWNER TO postgres;


DO language plpgsql $$BEGIN RAISE NOTICE 'Creating public.order...';END$$;
CREATE TABLE public."order" (
    "orderID" int2vector NOT NULL,
    "customerID" int2vector NOT NULL,
    "orderDate" date NOT NULL,
    "shipperID" int2vector NOT NULL
);
ALTER TABLE public."order" ADD CONSTRAINT order_pkey PRIMARY KEY ("orderID");
ALTER TABLE public."order" OWNER TO postgres;


DO language plpgsql $$BEGIN RAISE NOTICE 'Creating public.customer...';END$$;
CREATE TABLE public.customer (
    "customerID" int2vector NOT NULL,
    "customerName" character varying NOT NULL,
    address character varying,
    note character varying
);
ALTER TABLE public.customer ADD CONSTRAINT customer_pkey PRIMARY KEY ("customerID");
ALTER TABLE public.customer OWNER TO postgres;


DO language plpgsql $$BEGIN RAISE NOTICE 'Creating public.campaign...';END$$;
CREATE TABLE public.campaign (
    "campaignID" int2vector NOT NULL,
    "campaignName" character varying NOT NULL,
    "campaignDesc" character varying
);
ALTER TABLE public.campaign ADD CONSTRAINT campaign_pkey PRIMARY KEY ("campaignID");
ALTER TABLE public.campaign OWNER TO postgres;


DO language plpgsql $$BEGIN RAISE NOTICE 'Creating public.vwOrder...';END$$;
CREATE VIEW public."vwOrder" ("orderID", "customerID", "orderDate", "productID") AS SELECT o."orderID",
    o."customerID",
    o."orderDate",
    od."productID"
   FROM (public."order" o
     JOIN public."orderDetails" od ON ((o."orderID" = od."orderID")));
ALTER VIEW public."vwOrder" OWNER TO postgres;

SET check_function_bodies = true;
