-- Script generated by Redgate Compare v1.19.7.13456
SET check_function_bodies = false;


DO language plpgsql $$BEGIN RAISE NOTICE 'Dropping public.campaign...';END$$;
DROP TABLE public.campaign;

SET check_function_bodies = true;
