-- Script generated by Redgate Compare v1.19.7.13456
SET check_function_bodies = false;


DO language plpgsql $$BEGIN RAISE NOTICE 'Dropping public.test...';END$$;
DROP TABLE public.test;

SET check_function_bodies = true;
