-- Script generated by Redgate Compare v1.19.7.13456
SET check_function_bodies = false;


DO language plpgsql $$BEGIN RAISE NOTICE 'Creating public.test...';END$$;
CREATE TABLE public.test (
    col1 "char"
);
ALTER TABLE public.test OWNER TO postgres;

SET check_function_bodies = true;
