-- Script generated by Redgate Compare v1.19.7.13456
SET check_function_bodies = false;


DO language plpgsql $$BEGIN RAISE NOTICE 'Dropping public.testingForFluff...';END$$;
DROP TABLE public."testingForFluff";

SET check_function_bodies = true;
