-- Script generated by Redgate Compare v1.19.7.13456
SET check_function_bodies = false;


DO language plpgsql $$BEGIN RAISE NOTICE 'Dropping public.testTableForFlywayPipeline...';END$$;
DROP TABLE public."testTableForFlywayPipeline";

SET check_function_bodies = true;
