-- Script generated by Redgate Compare v1.19.7.13456
SET check_function_bodies = false;


DO language plpgsql $$BEGIN RAISE NOTICE 'Creating public.campaign...';END$$;
CREATE TABLE public.campaign (
    "campaignID" int2vector NOT NULL,
    "campaignName" character varying NOT NULL,
    "campaignDesc" character varying
);
ALTER TABLE public.campaign ADD CONSTRAINT campaign_pkey PRIMARY KEY ("campaignID");
ALTER TABLE public.campaign OWNER TO postgres;

SET check_function_bodies = true;
