-- Script generated by Redgate Compare v1.19.7.13456
SET check_function_bodies = false;


DO language plpgsql $$BEGIN RAISE NOTICE 'Creating public.purchaseOrders...';END$$;
CREATE TABLE public."purchaseOrders" (
                    "purchaseOrderID" int2vector NOT NULL,
    "customerID" int2vector NOT NULL
);
ALTER TABLE public."purchaseOrders" ADD CONSTRAINT "purchaseOrders_pkey" PRIMARY KEY ("purchaseOrderID");
ALTER TABLE public."purchaseOrders" OWNER TO postgres;


DO language plpgsql $$BEGIN RAISE NOTICE 'Creating public.orderDetails.fk_orderOrderDetails...';END$$;
ALTER TABLE public."orderDetails" ADD CONSTRAINT "fk_orderOrderDetails" FOREIGN KEY ("orderID") REFERENCES public."order" ("orderID");

SET             check_function_bodies = true;                
