-- Script generated by Redgate Compare v1.19.7.13456
SET check_function_bodies = false;


DO language plpgsql $$BEGIN RAISE NOTICE 'Creating public.vwOrder...';END$$;
CREATE VIEW public."vwOrder" ("orderID", "customerID", "orderDate", "productID") AS SELECT o."orderID",
    o."customerID",o."orderDate",                 
    od."productID"
   FROM (public."order" o
JOIN public."orderDetails" od ON ((o."orderID" = od."orderID")));
ALTER VIEW public."vwOrder" OWNER TO postgres;

SET check_function_bodies = true;
