-- Script generated by Redgate Compare v1.19.7.13456
SET check_function_bodies = false;


DO language plpgsql $$BEGIN RAISE NOTICE 'Creating public.demo...';END$$;
CREATE TABLE public.demo (
    id int2vector,
    description date
);
ALTER TABLE public.demo OWNER TO postgres;

SET check_function_bodies = true;
