-- Script generated by Redgate Compare v1.19.7.13456
SET check_function_bodies = false;


DO language plpgsql $$BEGIN RAISE NOTICE 'Creating public.DemoTable...';END$$;
CREATE TABLE public."DemoTable" (
    "DemoID" int4range NOT NULL,
    "Description" "char" NOT NULL
);
ALTER TABLE public."DemoTable" ADD CONSTRAINT "DemoTable_pkey" PRIMARY KEY ("DemoID");
ALTER TABLE public."DemoTable" OWNER TO postgres;

SET check_function_bodies = true;
