-- Script generated by Redgate Compare v1.19.7.13456
SET check_function_bodies = false;


DO language plpgsql $$BEGIN RAISE NOTICE 'Creating public.testNoPk...';END$$;
CREATE TABLE public."testNoPk" (
    col bigint
);
ALTER TABLE public."testNoPk" OWNER TO postgres;

SET check_function_bodies = true;
