-- Script generated by Redgate Compare v1.19.7.13456
SET check_function_bodies = false;


DO language plpgsql $$BEGIN RAISE NOTICE 'Creating public.testingForFluff...';END$$;
CREATE TABLE public."testingForFluff" (
    test "char"
);
ALTER TABLE public."testingForFluff" OWNER TO postgres;

SET check_function_bodies = true;
