-- Script generated by Redgate Compare v1.19.7.13456
SET check_function_bodies = false;


DO language plpgsql $$BEGIN RAISE NOTICE 'Creating public.testTableForFlywayPipeline...';END$$;
CREATE TABLE public."testTableForFlywayPipeline" (
    "ID" int4range NOT NULL,
    "Description" character varying(30) NOT NULL
);
ALTER TABLE public."testTableForFlywayPipeline" ADD CONSTRAINT "testTableForFlywayPipeline_pkey" PRIMARY KEY ("ID");
ALTER TABLE public."testTableForFlywayPipeline" OWNER TO postgres;

SET check_function_bodies = true;
