#test for flyway action
name: testFlywayInstall
 
# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
 

jobs:
  test1:
    name: Test1
    runs-on: ubuntu-latest
    env: 
     license: ${{ secrets.FLYWAY_LICENSE_KEY }}
     
    steps:
      - uses: kenmuse/setup-flyway@v1
        with: 
         edition: 'enterprise'
                       
      - name: Version
        run: flyway -v -licenseKey="${{ env.license }}"
